#!/usr/bin/python3

import sys
import os
import os.path
import subprocess
import re
import random

from possumtypes import *


if (len(sys.argv) < 5)
	print """compresspics filename quality resizedpercentage replacelimit

Convenience script to see if an image can be compressed further without losing too much quality. Great for processing cell phone photos.

quality is the quality setting for the JPEG compressor and can be from 0 to 100.

resizedpercentage is a number from 1 to 100 denoting the new size of the image. Leave it at 100 for no processing.

replacelimit is a number from 1 to 100. If the new size is this percentage smaller than the old file, then the new file will be used. Otherwise, the old file will remain untouched.

Example usage:

	compresspic test.jpg 70 50 30

This will try to compress test.jpg while resizing it to half the original size. If the new file is more than 30% smaller than the original, then it will be used.

Released under the GPL by Jim Yu (me@pafera.com)"""
	sys.exit()

quality		=	int(sys.argv[2])
resize		=	int(sys.argv[3])
percentlimit	=	int(sys.argv[4])

oldpath	=	os.path.join(root, f)
newpath	=	'/tmp/' + 'compresspics'

subprocess.call(['convert', oldpath, '-resize', str(resize) + '%', '-quality', str(quality), newpath])

oldstats	=	os.stat(oldpath)
newstats	=	os.stat(newpath)

compressedpercentage	=	(float(oldstats.st_size) - newstats.st_size) / oldstats.st_size * 100;

if compressedpercentage > percentlimit:
	Print('Compressed {} {:.0f}%', oldpath, compressedpercentage)
	os.rename(newpath, oldpath)
else:
	Print('Only compressed {} {:.0f}%', oldpath, compressedpercentage)
	os.remove(newpath)
