#!/usr/bin/python3

import sys
import os
import os.path
import subprocess
import re
import random

# playrandom
#
# Plays random videos from a directory and its subdirectories
# taking care to avoid playing the same TV show twice if possible.
#
# TV series should be in the format
# Show name - S01E02 - Episode Name
# 
# Quite useful for those of us with kids!
#
# Released under the GPL by Jim Yu (me@pafera.com)

from possumtypes import *

# =====================================================================
def GetSeries(filename):
	series	=	filename.split(' - ')
	
	if len(series) > 1:
		return series[0]
	
	return ''

if (len(sys.argv) < 2)
	print """playrandom directory [searchterm] [additionalargs]
	
Randomly plays all found media files in directory and any given subdirectories using mpv. Great for keeping your kids entertained.

If your files are in the standard format Show Name - S01E01 - Show Title, this script will try to avoid playing shows from the same series twice in a row as much as possible.

Released under the GPL by Jim Yu (me@pafera.com)"""
	sys.exit();


filelist	=	[]
exp				=	re.compile('.*\.(avi|mp4|m4v|flv|mov|mkv|3gp|3gpp|ogv|mts|mpg|mpeg|wmv|oga|ogg|wma|mp3|m4a|rm|rmvb|webm)$', re.IGNORECASE)

searchparm	=	sys.argv[2] if len(sys.argv) > 2 else None

print("Using searchparm {}", searchparm)

for root, dirs, files in os.walk(os.path.abspath(sys.argv[1])):
	for f in files:
		if exp.match(f):
			if searchparm and searchparm not in f.lower():
					continue
					
			filelist.append([os.path.join(root, f), GetSeries(f)])

random.shuffle(filelist)

# Avoid playing two consecutive files from the same series if possible
l	=	len(filelist)

for i in range(0, l - 1):
	series1	=	filelist[i][1]
	series2	=	filelist[i + 1][1]
	
	if series1 == series2:
		for j in range(0, l - 2):
			if filelist[j][1] != series2 and filelist[j + 1][1] != series2 and filelist[j + 2][1] != series2:
				filelist[i + 1], filelist[j + 1]	=	filelist[j + 1], filelist[i + 1]
				break

homedir				=	os.path.expanduser('~')
playlistfile	=	os.path.join(homedir, '.config', '.playrandom')
playlist			=	open(playlistfile, 'w')

for f in filelist:
	playlist.write(f[0] + "\n")
	
playlist.close()

try:
	subprocess.call(['mpv', '-quiet', '-playlist', playlistfile] + sys.argv[3:])
except KeyboardInterrupt:
	print('Exiting...')

subprocess.call(['reset'])
