#!/usr/bin/python3

import subprocess
import os
import sys
import os.path

cmdline	=	['ffmpeg', '-i', sys.argv[1], '-c:v', 'libx265', '-preset', sys.argv[2], '-x265-params', 'crf=' + sys.argv[3], '-c:a', 'aac', '-strict', 'experimental', '-b:a', sys.argv[4]]
cmdline.extend(sys.argv[5:])
cmdline.append(sys.argv[1] + '.mp4')

subprocess.call(cmdline)
